# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f34238c3-08bc-43ad-a811-1a1195b60b00";
      fsType = "ext4";
    };

  fileSystems."/mnt/media/music" =
    { device = "192.168.2.12:/mnt/MasterPool/Media/Music";
      fsType = "nfs";
    };

  fileSystems."/mnt/media/tv" =
    { device = "192.168.2.12:/mnt/MasterPool/Media/TV";
      fsType = "nfs";
    };

  fileSystems."/mnt/media/downloads" =
    { device = "192.168.2.12:/mnt/MasterPool/Media/Downloads";
      fsType = "nfs";
    };

  fileSystems."/mnt/media/movies" =
    { device = "192.168.2.12:/mnt/MasterPool/Media/Movies";
      fsType = "nfs";
    };

  fileSystems."/mnt/docker" =
    { device = "/dev/disk/by-uuid/1b94c9d0-bbbf-40c7-8978-cc3fdbe5fcb1";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
