server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

- job_name: containers

  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:

  - json:
      expressions:
        attrs:

  - json:
      expressions:
        tag:
        app:
        group:
      source: attrs

  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: tag

  - labels:
      app:
      group:
      image_name:
      container_name:
      image_id:
      container_id:

  - docker: {}

# SSH/Secure/Sudo Logs
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      instance: nixos
      env: homelab
      job: secure
      __path__: /var/log/secure

