services:
  - name: "TV & Movies"
    items:
      - name: "Plex"
        logo: "assets/png/plex.png"
        subtitle: "Watch Movies & TV"
        tag: "media"
        url: "https://plex.homelab.bloodstiller.com"
        target: "_blank"

      - name: "Radarr"
        logo: "assets/png/radarr.png"
        subtitle: "Add Movies"
        tag: "media"
        url: "https://radarr.homelab.bloodstiller.com"
        target: "_blank"

      - name: "Sonarr"
        logo: "assets/png/sonarr.png"
        subtitle: "Add TV"
        tag: "media"
        url: "https://sonarr.homelab.bloodstiller.com"
        target: "_blank"

  - name: "Networking"
    items:
      - name: "Router"
        logo: "assets/png/asus-router.png"
        subtitle: "Asus Router"
        tag: "management"
        url: "https://router.homelab.bloodstiller.com"
        target: "_blank"

      - name: "Pihole 1"
        logo: "assets/png/pi-hole.png"
        subtitle: "Pihole"
        tag: "dns"
        url: "https://pihole.homelab.bloodstiller.com/admin"
        target: "_blank"

      - name: "Pihole 2"
        logo: "assets/png/pi-hole.png"
        subtitle: "Pihole"
        tag: "dns"
        url: "https://pihole2.homelab.bloodstiller.com/admin"
        target: "_blank"

  - name: "Storage/NAS"
    items:
      - name: "Truenas"
        logo: "assets/png/truenas-scale.png"
        subtitle: "Manage Truenas"
        tag: "management"
        url: "httpss://truenas.homelab.bloodstiller.com/ui/sessions/signin"
        target: "_blank"

  - name: "Proxmox"
    items:
      - name: "Proxmox PVE1"
        logo: "assets/png/proxmox.png"
        subtitle: "PVE1"
        tag: "management"
        url: "httpss://pve1.homelab.bloodstiller.com"
        target: "_blank"

      - name: "Proxmox PVE2"
        logo: "assets/png/proxmox.png"
        subtitle: "PVE2"
        tag: "management"
        url: "httpss://pve2.homelab.bloodstiller.com"
        target: "_blank"

      - name: "Proxmox Backup Server"
        logo: "assets/png/proxmox.png"
        subtitle: "Backup Server"
        tag: "management"
        url: "httpss://pbs.homelab.bloodstiller.com"
        target: "_blank"

  - name: "Downloads"
    items:
      - name: "Qbitorrent"
        logo: "assets/png/qbittorrent.png"
        subtitle: "Download Client"
        tag: "Downloads"
        url: "httpss://qbitorrent.homelab.bloodstiller.com"
        target: "_blank"

      - name: "prowlarr"
        logo: "assets/png/prowlarr.png"
        subtitle: "Indexer"
        tag: "Downloads"
        url: "https://prowlarr.homelab.bloodstiller.com"
        target: "_blank"

  - name: "Proton"
    items:
      - name: "Proton Mail"
        logo: "assets/png/proton-mail.png"
        subtitle: "Email"
        tag: "Email"
        url: "httpss://mail.protonmail.com/"
        target: "_blank"

      - name: "Proton Calendar"
        logo: "assets/png/proton-calendar.png"
        subtitle: "Calendar"
        tag: "Calendar"
        url: "httpss://calendar.protonmail.com/"
        target: "_blank"

  - name: "Music"
    items:
      - name: "lidarr"
        logo: "assets/png/lidarr.png"
        subtitle: "Add to music"
        tag: "music"
        url: "httpss://lidarr.homelab.bloodstiller.com"
        target: "_blank"




  - name: "Useful"
    items:
      - name: "WhatsApp"
        logo: "assets/png/whatsapp.png"
        subtitle: "Talk"
        tag: "Useful"
        url: "httpss://web.whatsapp.com/"
        target: "_blank"

      - name: "Amazon"
        logo: "assets/png/amazon.png"
        subtitle: "Buy"
        tag: "Useful"
        url: "httpss://www.amazon.co.uk/"
        target: "_blank"

      - name: "GitHub"
        logo: "assets/png/github.png"
        subtitle: "push"
        tag: "Useful"
        url: "httpss://github.com/"
        target: "_blank"
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'

# Will load Dracula theme.
stylesheet:
  - "assets/custom.css"
footer: false

connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
                        # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.