services:
  - name: "TV & Movies"
    items:
      - name: "Plex"
        logo: "assets/png/plex.png"
        subtitle: "Watch Movies & TV"
        tag: "media"
        url: "http://plex.homelab.bloodstiller.com"
        target: "_blank"

      - name: "Radarr"
        logo: "assets/png/radarr.png"
        subtitle: "Add Movies"
        tag: "media"
        url: "http://radarr.homelab.bloodstiller.com"
        target: "_blank"

      - name: "Sonarr"
        logo: "assets/png/sonarr.png"
        subtitle: "Add TV"
        tag: "media"
        url: "http://sonarr.homelab.bloodstiller.com"
        target: "_blank"

  - name: "Networking"
    items:
      - name: "Router"
        logo: "assets/png/asus-router.png"
        subtitle: "Asus Router"
        tag: "management"
        url: "http://router.homelab.bloodstiller.com"
        target: "_blank"

      - name: "Pihole 1"
        logo: "assets/png/pi-hole.png"
        subtitle: "Pihole"
        tag: "dns"
        url: "http://pihole.homelab.bloodstiller.com/admin"
        target: "_blank"

      - name: "Pihole 2"
        logo: "assets/png/pi-hole.png"
        subtitle: "Pihole"
        tag: "dns"
        url: "http://pihole2.homelab.bloodstiller.com/admin"
        target: "_blank"

      - name: "nginx-proxy-manager"
        logo: "assets/png/nginx-proxy-manager.png"
        subtitle: "nginx-proxy-manager"
        tag: "dns"
        url: "http://192.168.2.151:81"
        target: "_blank"

  - name: "Storage/NAS"
    items:
      - name: "Truenas"
        logo: "assets/png/truenas-scale.png"
        subtitle: "Manage Truenas"
        tag: "management"
        url: "https://truenas.homelab.bloodstiller.com/ui/sessions/signin"
        target: "_blank"

  - name: "Proxmox"
    items:
      - name: "Proxmox PVE1"
        logo: "assets/png/proxmox.png"
        subtitle: "PVE1"
        tag: "management"
        url: "https://pve1.homelab.bloodstiller.com"
        target: "_blank"

      - name: "Proxmox PVE2"
        logo: "assets/png/proxmox.png"
        subtitle: "PVE2"
        tag: "management"
        url: "https://pve2.homelab.bloodstiller.com"
        target: "_blank"

      - name: "Proxmox Backup Server"
        logo: "assets/png/proxmox.png"
        subtitle: "Backup Server"
        tag: "management"
        url: "https://pbs.homelab.bloodstiller.com"
        target: "_blank"

  - name: "Downloads"
    items:
      - name: "Qbitorrent"
        logo: "assets/png/qbittorrent.png"
        subtitle: "Download Client"
        tag: "Downloads"
        url: "http://qbitorrent.homelab.bloodstiller.com"
        target: "_blank"

      - name: "prowlarr"
        logo: "assets/png/prowlarr.png"
        subtitle: "Indexer"
        tag: "Downloads"
        url: "http://prowlarr.homelab.bloodstiller.com"
        target: "_blank"

  - name: "Proton"
    items:
      - name: "Proton Mail"
        logo: "assets/png/proton-mail.png"
        subtitle: "Email"
        tag: "Email"
        url: "https://mail.protonmail.com/"
        target: "_blank"

      - name: "Proton Calendar"
        logo: "assets/png/proton-calendar.png"
        subtitle: "Calendar"
        tag: "Calendar"
        url: "https://calendar.protonmail.com/"
        target: "_blank"

  - name: "Music"
    items:
      - name: "lidarr"
        logo: "assets/png/lidarr.png"
        subtitle: "Add to music"
        tag: "music"
        url: "https://lidarr.homelab.bloodstiller.com"
        target: "_blank"




  - name: "Useful"
    items:
      - name: "WhatsApp"
        logo: "assets/png/whatsapp.png"
        subtitle: "Talk"
        tag: "Useful"
        url: "https://web.whatsapp.com/"
        target: "_blank"

      - name: "Amazon"
        logo: "assets/png/amazon.png"
        subtitle: "Buy"
        tag: "Useful"
        url: "https://www.amazon.co.uk/"
        target: "_blank"

      - name: "GitHub"
        logo: "assets/png/github.png"
        subtitle: "push"
        tag: "Useful"
        url: "https://github.com/"
        target: "_blank"
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'

# Will load Dracula theme.
stylesheet:
  - "assets/custom.css"
footer: false

connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
                        # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.